/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntroductionRouteImport } from './routes/introduction'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as OutcomesIndexRouteImport } from './routes/outcomes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as SkillsSlugRouteImport } from './routes/skills/$slug'
import { Route as OutcomesSlugRouteImport } from './routes/outcomes/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'

const IntroductionRoute = IntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesIndexRoute = OutcomesIndexRouteImport.update({
  id: '/outcomes/',
  path: '/outcomes/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesSlugRoute = OutcomesSlugRouteImport.update({
  id: '/outcomes/$slug',
  path: '/outcomes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/introduction': typeof IntroductionRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/outcomes/$slug': typeof OutcomesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/outcomes/': typeof OutcomesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/introduction': typeof IntroductionRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/outcomes/$slug': typeof OutcomesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/outcomes': typeof OutcomesIndexRoute
  '/skills': typeof SkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/introduction': typeof IntroductionRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/outcomes/$slug': typeof OutcomesSlugRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/outcomes/': typeof OutcomesIndexRoute
  '/skills/': typeof SkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/introduction'
    | '/guides/$slug'
    | '/outcomes/$slug'
    | '/skills/$slug'
    | '/guides/'
    | '/outcomes/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/introduction'
    | '/guides/$slug'
    | '/outcomes/$slug'
    | '/skills/$slug'
    | '/guides'
    | '/outcomes'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/introduction'
    | '/guides/$slug'
    | '/outcomes/$slug'
    | '/skills/$slug'
    | '/guides/'
    | '/outcomes/'
    | '/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntroductionRoute: typeof IntroductionRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  OutcomesSlugRoute: typeof OutcomesSlugRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  OutcomesIndexRoute: typeof OutcomesIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/': {
      id: '/outcomes/'
      path: '/outcomes'
      fullPath: '/outcomes/'
      preLoaderRoute: typeof OutcomesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/$slug': {
      id: '/outcomes/$slug'
      path: '/outcomes/$slug'
      fullPath: '/outcomes/$slug'
      preLoaderRoute: typeof OutcomesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntroductionRoute: IntroductionRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  OutcomesSlugRoute: OutcomesSlugRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  OutcomesIndexRoute: OutcomesIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
